[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
  'npm install --prefer-offline --no-audit --no-fund'
]

[phases.build]
cmds = ['echo "No build step required"']

[start]
cmd = 'npm start'
