[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x']

[phases.install]
cmds = [
  'npm install --prefer-offline --no-audit --no-fund --cache /tmp/.npm'
]

[phases.build]
cmds = ['echo "No build step required"']

[start]
cmd = 'npm start'
